<a href="https://colab.research.google.com/github/lokwq/TextBrewer/blob/add_note_examples/sst2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook shows how to fine-tune a model on sst-2 dataset and how to distill the model with TextBrewer.

Detailed Docs can be find here:
https://github.com/airaria/TextBrewer

In [2]:
import torch
device='cuda' if torch.cuda.is_available() else 'cpu'
#device = 'cpu'

In [8]:
import os
import torch
from transformers import BertForSequenceClassification, BertTokenizer,BertConfig, AutoModelForSequenceClassification,RobertaTokenizer, RobertaForSequenceClassification
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import Trainer, TrainingArguments
from datasets import load_dataset,load_metric
from functools import partial
from predict_function import predict

### Prepare dataset to train

In [5]:
train_dataset = load_dataset('glue', 'stsb', split='train')#,cache_dir="/work/mhessent/cache")
val_dataset = load_dataset('glue', 'stsb', split='validation')#,cache_dir="/work/mhessent/cache")
test_dataset = load_dataset('glue', 'stsb', split='test')#,cache_dir="/work/mhessent/cache")

Reusing dataset glue (/home/mhessent/.cache/huggingface/datasets/glue/stsb/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
Reusing dataset glue (/home/mhessent/.cache/huggingface/datasets/glue/stsb/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
Reusing dataset glue (/home/mhessent/.cache/huggingface/datasets/glue/stsb/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)


In [6]:
train_dataset = train_dataset.map(lambda examples: {'labels': examples['label']}, batched=True)
val_dataset = val_dataset.map(lambda examples: {'labels': examples['label']}, batched=True)
test_dataset = test_dataset.map(lambda examples: {'labels': examples['label']}, batched=True)

val_dataset = val_dataset.remove_columns(['label'])
test_dataset = test_dataset.remove_columns(['label'])
train_dataset = train_dataset.remove_columns(['label'])

Loading cached processed dataset at /home/mhessent/.cache/huggingface/datasets/glue/stsb/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-2a1905efa4704bcb.arrow
Loading cached processed dataset at /home/mhessent/.cache/huggingface/datasets/glue/stsb/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-e194e0b596fcf478.arrow
Loading cached processed dataset at /home/mhessent/.cache/huggingface/datasets/glue/stsb/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-c97e180e5b68e6bf.arrow


In [9]:
#model = RobertaForSequenceClassification.from_pretrained('roberta-base', num_labels=1)
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

In [10]:
MAX_LENGTH = 128
train_dataset = train_dataset.map(lambda e: tokenizer(e['sentence1'],e['sentence2'], truncation=True, padding='max_length', max_length=MAX_LENGTH), batched=True)
val_dataset = val_dataset.map(lambda e: tokenizer(e['sentence1'],e['sentence2'], truncation=True, padding='max_length', max_length=MAX_LENGTH), batched=True)
test_dataset = test_dataset.map(lambda e: tokenizer(e['sentence1'],e['sentence2'], truncation=True, padding='max_length', max_length=MAX_LENGTH), batched=True)

  0%|          | 0/6 [00:00<?, ?ba/s]

  0%|          | 0/2 [00:00<?, ?ba/s]

  0%|          | 0/2 [00:00<?, ?ba/s]

In [11]:
train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
val_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

In [29]:
train_dataset[1]

{'labels': tensor(3.8000),
 'input_ids': tensor([   0,  250,  313,   16,  816,   10,  739, 2342, 4467,    4,    2,    2,
          250,  313,   16,  816,   10, 2342, 4467,    4,    2,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0

In [30]:
val_dataset[1]

{'labels': tensor(4.7500),
 'input_ids': tensor([   0,  250,  664,  920,   16, 5793,   10, 5253,    4,    2,    2,  250,
          920,   16, 5793,   10, 5253,    4,    2,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0

In [13]:

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    metric = load_metric("glue","stsb")
    return metric.compute(predictions=preds, references=labels)


In [ ]:
#start training 

training_args = TrainingArguments(
    output_dir='outputs/results',          #output directory
    learning_rate=3e-5,
    num_train_epochs=3,              
    per_device_train_batch_size=32,                #batch size per device during training
    per_device_eval_batch_size=32,                #batch size for evaluation
    logging_dir='outputs/logs',            
    logging_steps=500,
    do_train=True,
    do_eval=True,
    no_cuda=False,
    load_best_model_at_end=True,
    # eval_steps=100,
    evaluation_strategy="epoch",
    save_strategy="epoch"
)

trainer = Trainer(
    model=model,                         
    args=training_args,                  
    train_dataset=train_dataset,         
    eval_dataset=val_dataset,            
    compute_metrics=compute_metrics
)

train_out = trainer.train()

#after training, you could find traing logs and checpoints in your own dirve. also you can reset the file address in training args

In [44]:
#torch.save(model.state_dict(), 'outputs/stsb_teacher_model.pt')


/work/mhessent/miniconda/envs/thesis_test/lib/python3.8/site-packages/torch/nn/modules/module.py:1385: UserWarning: positional arguments and argument "destination" are deprecated. nn.Module.state_dict will not accept them in the future. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(


### Start distillation

In [14]:
train_dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=32) #prepare dataloader

In [15]:
import textbrewer
from textbrewer import GeneralDistiller
from textbrewer import TrainingConfig, DistillationConfig
from transformers import BertForSequenceClassification, BertConfig, AdamW,BertTokenizer, RobertaConfig, RobertaForSequenceClassification
from transformers import get_linear_schedule_with_warmup

In [16]:
config = RobertaConfig.from_pretrained("roberta-base", output_hidden_states=True)
config

RobertaConfig {
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_hidden_states": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.17.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

In [20]:
distilroberta_config = RobertaConfig.from_pretrained("distilroberta-base", output_hidden_states=True)
distilroberta_config

Downloading:   0%|          | 0.00/480 [00:00<?, ?B/s]

RobertaConfig {
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "output_hidden_states": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.17.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

Initialize the student model by BertConfig and prepare the teacher model.

bert_config_L3.json refers to a 3-layer Bert.

bert_config.json refers to a standard 12-layer Bert.

In [31]:
config = RobertaConfig.from_pretrained("roberta-base", output_hidden_states=True)
#config = RobertaConfig.from_json_file('/work/mhessent/TextBrewer/examples/student_config/bert_base_cased_config/bert_config.json')
config.output_hidden_states = True
#config.vocab_size = len(tokenizer)
config.num_labels = 1

teacher_model = RobertaForSequenceClassification(config)
#teacher_model.load_state_dict(torch.load('/work/mhessent/master_thesis/eval_out/roberta-base/stsb/lr3e-05_bs16_epochs10/torch_state_dict.pt'))
teacher_model.load_state_dict(torch.load('outputs/stsb_teacher_model.pt'))
"""
model = BertForSequenceClassification.from_pretrained("/work/mhessent/master_thesis/eval_out/bert-base-uncased/mnli/lr3e-05_bs32_epochs3/checkpoint-36816")
torch.save(model.state_dict(), 'outputs/hub_mnli_teacher_model.pt')
bert_config = BertConfig.from_json_file('/work/mhessent/TextBrewer/examples/student_config/bert_base_cased_config/bert_config.json')
bert_config.output_hidden_states = True
bert_config.vocab_size = 30522
bert_config.num_labels = 3
teacher_model = BertForSequenceClassification(bert_config) #, num_labels = 2
teacher_model.load_state_dict(torch.load('outputs/hub_mnli_teacher_model.pt'))
"""


teacher_model = teacher_model.to(device=device)



student_config = RobertaConfig.from_pretrained("roberta-base", output_hidden_states=True)
student_config.output_hidden_states = True
student_config.num_labels = 1
student_config.num_hidden_layers = 3
#student_config.vocab_size = teacher_model.config.vocab_size

student_model = RobertaForSequenceClassification(student_config)
student_model = student_model.to(device=device)


print(teacher_model.config.vocab_size)
print(student_model.config.vocab_size)
print(len(tokenizer))

50265
50265
50265


The cell below is to distill the teacher model to student model you prepared.

After the code execution is complete, the distilled model will be in 'saved_model' in colab file list

In [22]:
num_epochs = 60
num_training_steps = len(train_dataloader) * num_epochs
# Optimizer and learning rate scheduler
optimizer = AdamW(student_model.parameters(), lr=1e-4)

scheduler_class = get_linear_schedule_with_warmup
# arguments dict except 'optimizer'
scheduler_args = {'num_warmup_steps':int(0.1*num_training_steps), 'num_training_steps':num_training_steps}


def simple_adaptor(batch, model_outputs):
    return {'logits': model_outputs.logits, 'hidden': model_outputs.hidden_states}


from matches import matches
intermediate_matches = None
match_list_L4t = ["L4t_hidden_mse", "L4_hidden_smmd"]
match_list_L3 = ["L3_hidden_mse", "L3_hidden_smmd"]
intermediate_matches = []
for match in match_list_L3:
        intermediate_matches += matches[match]

distill_config = DistillationConfig(kd_loss_type='mse')#,intermediate_matches=intermediate_matches)
train_config = TrainingConfig(device=device)



task_name = "stsb"
local_rank = -1
predict_batch_size = 32
device = device
output_dir = "outputs/" + task_name + "/" 
eval_datasets = [val_dataset]

callback_func = partial(predict, eval_datasets=eval_datasets, output_dir=output_dir,task_name=task_name,local_rank=local_rank,predict_batch_size=predict_batch_size,device=device)

distiller = GeneralDistiller(
    train_config=train_config, distill_config=distill_config,
    model_T=teacher_model, model_S=student_model, 
    adaptor_T=simple_adaptor, adaptor_S=simple_adaptor)


with distiller:
    distiller.train(optimizer, train_dataloader, num_epochs, scheduler_class=scheduler_class, scheduler_args = scheduler_args, callback=callback_func)

2022/03/29 14:17:31 - INFO - Distillation -  Training steps per epoch: 180
2022/03/29 14:17:31 - INFO - Distillation -  Checkpoints(step): [0]
2022/03/29 14:17:31 - INFO - Distillation -  Epoch 1
2022/03/29 14:17:31 - INFO - Distillation -  Length of current epoch in forward batch: 180
2022/03/29 14:17:33 - INFO - Distillation -  Global step: 9, epoch step:9
2022/03/29 14:17:34 - INFO - Distillation -  Global step: 18, epoch step:18
2022/03/29 14:17:36 - INFO - Distillation -  Global step: 27, epoch step:27
2022/03/29 14:17:37 - INFO - Distillation -  Global step: 36, epoch step:36
2022/03/29 14:17:39 - INFO - Distillation -  Global step: 45, epoch step:45
2022/03/29 14:17:41 - INFO - Distillation -  Global step: 54, epoch step:54
2022/03/29 14:17:42 - INFO - Distillation -  Global step: 63, epoch step:63
2022/03/29 14:17:44 - INFO - Distillation -  Global step: 72, epoch step:72
2022/03/29 14:17:45 - INFO - Distillation -  Global step: 81, epoch step:81
2022/03/29 14:17:47 - INFO - Di

tensor([[2.9424],
        [2.9448]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9757],
        [2.9587]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9740],
        [2.9554]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9558],
        [2.9617]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9618],
        [2.9602]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9493],
        [2.9550]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9513],
        [2.9711]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9760],
        [2.9768]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9604],
        [2.9468]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9739],
        [2.9736]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9659],
        [2.9698]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9652],
        [2.9676]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9741],
        [2.9546]], dev

2022/03/29 14:18:09 - INFO - Distillation -  {'pearson': 0.0062128703980162975, 'spearmanr': 0.007232440076709042}
2022/03/29 14:18:09 - INFO - Distillation -  Epoch 1 finished
2022/03/29 14:18:09 - INFO - Distillation -  Epoch 2
2022/03/29 14:18:09 - INFO - Distillation -  Length of current epoch in forward batch: 180
2022/03/29 14:18:10 - INFO - Distillation -  Global step: 189, epoch step:9
2022/03/29 14:18:12 - INFO - Distillation -  Global step: 198, epoch step:18
2022/03/29 14:18:13 - INFO - Distillation -  Global step: 207, epoch step:27
2022/03/29 14:18:15 - INFO - Distillation -  Global step: 216, epoch step:36
2022/03/29 14:18:17 - INFO - Distillation -  Global step: 225, epoch step:45
2022/03/29 14:18:18 - INFO - Distillation -  Global step: 234, epoch step:54
2022/03/29 14:18:20 - INFO - Distillation -  Global step: 243, epoch step:63
2022/03/29 14:18:21 - INFO - Distillation -  Global step: 252, epoch step:72
2022/03/29 14:18:23 - INFO - Distillation -  Global step: 261, e

tensor([[3.0988],
        [3.0961]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1558],
        [3.0966]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1494],
        [3.0932]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1175],
        [3.1200]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1316],
        [3.1344]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0954],
        [3.0989]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1013],
        [3.1444]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1452],
        [3.1720]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1359],
        [3.1237]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1636],
        [3.1780]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1587],
        [3.1486]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1434],
        [3.1531]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1513],
        [3.1263]], dev

2022/03/29 14:18:44 - INFO - Distillation -  {'pearson': 0.06229257444329203, 'spearmanr': 0.06758987962503035}
2022/03/29 14:18:44 - INFO - Distillation -  Epoch 2 finished
2022/03/29 14:18:44 - INFO - Distillation -  Epoch 3
2022/03/29 14:18:44 - INFO - Distillation -  Length of current epoch in forward batch: 180
2022/03/29 14:18:46 - INFO - Distillation -  Global step: 369, epoch step:9
2022/03/29 14:18:47 - INFO - Distillation -  Global step: 378, epoch step:18
2022/03/29 14:18:49 - INFO - Distillation -  Global step: 387, epoch step:27
2022/03/29 14:18:51 - INFO - Distillation -  Global step: 396, epoch step:36
2022/03/29 14:18:52 - INFO - Distillation -  Global step: 405, epoch step:45
2022/03/29 14:18:54 - INFO - Distillation -  Global step: 414, epoch step:54
2022/03/29 14:18:55 - INFO - Distillation -  Global step: 423, epoch step:63
2022/03/29 14:18:57 - INFO - Distillation -  Global step: 432, epoch step:72
2022/03/29 14:18:59 - INFO - Distillation -  Global step: 441, epoc

tensor([[3.1054],
        [3.0991]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.3637],
        [2.9882]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1327],
        [2.9827]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0415],
        [3.0722]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1510],
        [3.2015]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0072],
        [2.9972]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0036],
        [3.1027]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0936],
        [3.2958]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.2942],
        [3.2917]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.2353],
        [3.4094]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.3876],
        [3.3594]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.3227],
        [3.3568]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1369],
        [3.1951]], dev

2022/03/29 14:19:20 - INFO - Distillation -  {'pearson': 0.13227673441926008, 'spearmanr': 0.15243127450458419}
2022/03/29 14:19:20 - INFO - Distillation -  Epoch 3 finished
2022/03/29 14:19:20 - INFO - Distillation -  Epoch 4
2022/03/29 14:19:20 - INFO - Distillation -  Length of current epoch in forward batch: 180


tensor([[3.2401],
        [3.3621]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.2989],
        [3.3802]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.4108],
        [3.3859]], device='cuda:0', grad_fn=<SliceBackward0>)


2022/03/29 14:19:22 - INFO - Distillation -  Global step: 549, epoch step:9
2022/03/29 14:19:23 - INFO - Distillation -  Global step: 558, epoch step:18
2022/03/29 14:19:25 - INFO - Distillation -  Global step: 567, epoch step:27
2022/03/29 14:19:26 - INFO - Distillation -  Global step: 576, epoch step:36
2022/03/29 14:19:28 - INFO - Distillation -  Global step: 585, epoch step:45
2022/03/29 14:19:30 - INFO - Distillation -  Global step: 594, epoch step:54
2022/03/29 14:19:31 - INFO - Distillation -  Global step: 603, epoch step:63
2022/03/29 14:19:33 - INFO - Distillation -  Global step: 612, epoch step:72
2022/03/29 14:19:34 - INFO - Distillation -  Global step: 621, epoch step:81
2022/03/29 14:19:36 - INFO - Distillation -  Global step: 630, epoch step:90
2022/03/29 14:19:38 - INFO - Distillation -  Global step: 639, epoch step:99
2022/03/29 14:19:40 - INFO - Distillation -  Global step: 648, epoch step:108
2022/03/29 14:19:41 - INFO - Distillation -  Global step: 657, epoch step:11

tensor([[2.8005],
        [2.7488]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.4294],
        [2.4678]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.8322],
        [2.4491]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.5718],
        [2.6507]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.8942],
        [2.9740]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.4484],
        [2.5208]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.3950],
        [2.7477]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.6484],
        [3.1513]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.2225],
        [3.1000]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0653],
        [3.5214]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.5290],
        [3.4382]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1890],
        [3.3816]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.8533],
        [2.9493]], dev

2022/03/29 14:19:57 - INFO - Distillation -  {'pearson': 0.15934024242720646, 'spearmanr': 0.17108323906281053}
2022/03/29 14:19:57 - INFO - Distillation -  Epoch 4 finished
2022/03/29 14:19:57 - INFO - Distillation -  Epoch 5
2022/03/29 14:19:57 - INFO - Distillation -  Length of current epoch in forward batch: 180


tensor([[3.2574],
        [3.4611]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.4115],
        [3.3222]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0445],
        [3.3994]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.2287],
        [3.4542]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.6090],
        [3.5566]], device='cuda:0', grad_fn=<SliceBackward0>)


2022/03/29 14:19:59 - INFO - Distillation -  Global step: 729, epoch step:9
2022/03/29 14:20:00 - INFO - Distillation -  Global step: 738, epoch step:18
2022/03/29 14:20:02 - INFO - Distillation -  Global step: 747, epoch step:27
2022/03/29 14:20:04 - INFO - Distillation -  Global step: 756, epoch step:36
2022/03/29 14:20:05 - INFO - Distillation -  Global step: 765, epoch step:45
2022/03/29 14:20:07 - INFO - Distillation -  Global step: 774, epoch step:54
2022/03/29 14:20:09 - INFO - Distillation -  Global step: 783, epoch step:63
2022/03/29 14:20:10 - INFO - Distillation -  Global step: 792, epoch step:72
2022/03/29 14:20:12 - INFO - Distillation -  Global step: 801, epoch step:81
2022/03/29 14:20:14 - INFO - Distillation -  Global step: 810, epoch step:90
2022/03/29 14:20:16 - INFO - Distillation -  Global step: 819, epoch step:99
2022/03/29 14:20:17 - INFO - Distillation -  Global step: 828, epoch step:108
2022/03/29 14:20:19 - INFO - Distillation -  Global step: 837, epoch step:11

tensor([[-0.1315],
        [ 0.1668]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[ 1.5116],
        [-0.2669]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[-0.4240],
        [-0.7050]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[-0.6668],
        [-0.4031]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.4880],
        [0.4843]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[-0.7998],
        [-0.2885]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[-0.5885],
        [-0.1288]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[-0.3194],
        [ 0.8376]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.6410],
        [0.8590]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.2569],
        [1.4199]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.4414],
        [2.3851]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.8136],
        [0.9844]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[-0.4715],
       

2022/03/29 14:20:34 - INFO - Distillation -  {'pearson': 0.17703075060689014, 'spearmanr': 0.16909775889461354}
2022/03/29 14:20:34 - INFO - Distillation -  Epoch 5 finished
2022/03/29 14:20:34 - INFO - Distillation -  Epoch 6
2022/03/29 14:20:34 - INFO - Distillation -  Length of current epoch in forward batch: 180


tensor([[1.9097],
        [1.2845]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.1246],
        [2.0121]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.9054],
        [2.7647]], device='cuda:0', grad_fn=<SliceBackward0>)


2022/03/29 14:20:36 - INFO - Distillation -  Global step: 909, epoch step:9
2022/03/29 14:20:37 - INFO - Distillation -  Global step: 918, epoch step:18
2022/03/29 14:20:39 - INFO - Distillation -  Global step: 927, epoch step:27
2022/03/29 14:20:41 - INFO - Distillation -  Global step: 936, epoch step:36
2022/03/29 14:20:42 - INFO - Distillation -  Global step: 945, epoch step:45
2022/03/29 14:20:44 - INFO - Distillation -  Global step: 954, epoch step:54
2022/03/29 14:20:45 - INFO - Distillation -  Global step: 963, epoch step:63
2022/03/29 14:20:47 - INFO - Distillation -  Global step: 972, epoch step:72
2022/03/29 14:20:49 - INFO - Distillation -  Global step: 981, epoch step:81
2022/03/29 14:20:51 - INFO - Distillation -  Global step: 990, epoch step:90
2022/03/29 14:20:52 - INFO - Distillation -  Global step: 999, epoch step:99
2022/03/29 14:20:54 - INFO - Distillation -  Global step: 1008, epoch step:108
2022/03/29 14:20:56 - INFO - Distillation -  Global step: 1017, epoch step:

tensor([[0.7247],
        [0.9674]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.9320],
        [4.2611]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.1678],
        [0.9314]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.9403],
        [1.4562]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.1566],
        [1.8425]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.5687],
        [1.6763]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.6523],
        [1.6298]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.5430],
        [3.2536]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.4773],
        [2.3434]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.7192],
        [3.0245]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.9718],
        [4.9926]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.0443],
        [1.1787]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.4525],
        [1.7747]], dev

2022/03/29 14:21:11 - INFO - Distillation -  {'pearson': 0.16042464796731964, 'spearmanr': 0.16240458524238655}
2022/03/29 14:21:11 - INFO - Distillation -  Epoch 6 finished
2022/03/29 14:21:11 - INFO - Distillation -  Epoch 7
2022/03/29 14:21:11 - INFO - Distillation -  Length of current epoch in forward batch: 180
2022/03/29 14:21:13 - INFO - Distillation -  Global step: 1089, epoch step:9
2022/03/29 14:21:15 - INFO - Distillation -  Global step: 1098, epoch step:18
2022/03/29 14:21:16 - INFO - Distillation -  Global step: 1107, epoch step:27
2022/03/29 14:21:18 - INFO - Distillation -  Global step: 1116, epoch step:36
2022/03/29 14:21:20 - INFO - Distillation -  Global step: 1125, epoch step:45
2022/03/29 14:21:21 - INFO - Distillation -  Global step: 1134, epoch step:54
2022/03/29 14:21:23 - INFO - Distillation -  Global step: 1143, epoch step:63
2022/03/29 14:21:24 - INFO - Distillation -  Global step: 1152, epoch step:72
2022/03/29 14:21:26 - INFO - Distillation -  Global step: 1

tensor([[0.7503],
        [1.7168]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.7183],
        [4.8514]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.5913],
        [1.5322]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.1791],
        [3.3263]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.5397],
        [5.1231]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.2236],
        [2.5083]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.2861],
        [2.5676]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.8419],
        [3.7971]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.7863],
        [4.6555]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.8343],
        [4.2799]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[5.1150],
        [5.1210]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.0180],
        [1.5360]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1107],
        [3.0869]], dev

2022/03/29 14:21:48 - INFO - Distillation -  {'pearson': 0.15035060434078906, 'spearmanr': 0.15460839659506215}
2022/03/29 14:21:48 - INFO - Distillation -  Epoch 7 finished
2022/03/29 14:21:48 - INFO - Distillation -  Epoch 8
2022/03/29 14:21:48 - INFO - Distillation -  Length of current epoch in forward batch: 180
2022/03/29 14:21:50 - INFO - Distillation -  Global step: 1269, epoch step:9
2022/03/29 14:21:52 - INFO - Distillation -  Global step: 1278, epoch step:18
2022/03/29 14:21:53 - INFO - Distillation -  Global step: 1287, epoch step:27
2022/03/29 14:21:55 - INFO - Distillation -  Global step: 1296, epoch step:36
2022/03/29 14:21:56 - INFO - Distillation -  Global step: 1305, epoch step:45
2022/03/29 14:21:58 - INFO - Distillation -  Global step: 1314, epoch step:54
2022/03/29 14:22:00 - INFO - Distillation -  Global step: 1323, epoch step:63
2022/03/29 14:22:01 - INFO - Distillation -  Global step: 1332, epoch step:72
2022/03/29 14:22:03 - INFO - Distillation -  Global step: 1

tensor([[0.8871],
        [2.9454]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.9635],
        [5.1098]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.1273],
        [2.4144]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.6688],
        [4.7075]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[5.2130],
        [5.2778]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.1806],
        [3.6606]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.2122],
        [3.5949]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.8308],
        [5.1018]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.8810],
        [4.5471]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[5.0987],
        [4.7531]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[5.4768],
        [5.3627]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.8701],
        [1.5432]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.8651],
        [3.3598]], dev

2022/03/29 14:22:25 - INFO - Distillation -  {'pearson': 0.16603823840472687, 'spearmanr': 0.17297136654659473}
2022/03/29 14:22:25 - INFO - Distillation -  Epoch 8 finished
2022/03/29 14:22:25 - INFO - Distillation -  Epoch 9
2022/03/29 14:22:25 - INFO - Distillation -  Length of current epoch in forward batch: 180


tensor([[5.2627],
        [5.4904]], device='cuda:0', grad_fn=<SliceBackward0>)


2022/03/29 14:22:27 - INFO - Distillation -  Global step: 1449, epoch step:9
2022/03/29 14:22:28 - INFO - Distillation -  Global step: 1458, epoch step:18
2022/03/29 14:22:30 - INFO - Distillation -  Global step: 1467, epoch step:27
2022/03/29 14:22:32 - INFO - Distillation -  Global step: 1476, epoch step:36
2022/03/29 14:22:33 - INFO - Distillation -  Global step: 1485, epoch step:45
2022/03/29 14:22:35 - INFO - Distillation -  Global step: 1494, epoch step:54
2022/03/29 14:22:37 - INFO - Distillation -  Global step: 1503, epoch step:63
2022/03/29 14:22:39 - INFO - Distillation -  Global step: 1512, epoch step:72
2022/03/29 14:22:40 - INFO - Distillation -  Global step: 1521, epoch step:81
2022/03/29 14:22:42 - INFO - Distillation -  Global step: 1530, epoch step:90
2022/03/29 14:22:44 - INFO - Distillation -  Global step: 1539, epoch step:99
2022/03/29 14:22:45 - INFO - Distillation -  Global step: 1548, epoch step:108
2022/03/29 14:22:47 - INFO - Distillation -  Global step: 1557, 

tensor([[0.6802],
        [2.2644]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.9483],
        [4.6112]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.8039],
        [1.8317]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.3673],
        [3.9797]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.8870],
        [4.6993]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.7265],
        [3.5946]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.5110],
        [2.0104]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.3760],
        [4.8968]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.4551],
        [4.4454]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[5.1010],
        [3.1330]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[5.4980],
        [5.3110]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.5325],
        [1.5322]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.6001],
        [0.7859]], dev

2022/03/29 14:23:02 - INFO - Distillation -  {'pearson': 0.1510390726318039, 'spearmanr': 0.14478096099615667}
2022/03/29 14:23:02 - INFO - Distillation -  Epoch 9 finished
2022/03/29 14:23:02 - INFO - Distillation -  Epoch 10
2022/03/29 14:23:02 - INFO - Distillation -  Length of current epoch in forward batch: 180


tensor([[4.7583],
        [5.3344]], device='cuda:0', grad_fn=<SliceBackward0>)


2022/03/29 14:23:04 - INFO - Distillation -  Global step: 1629, epoch step:9
2022/03/29 14:23:05 - INFO - Distillation -  Global step: 1638, epoch step:18
2022/03/29 14:23:07 - INFO - Distillation -  Global step: 1647, epoch step:27
2022/03/29 14:23:09 - INFO - Distillation -  Global step: 1656, epoch step:36
2022/03/29 14:23:10 - INFO - Distillation -  Global step: 1665, epoch step:45
2022/03/29 14:23:12 - INFO - Distillation -  Global step: 1674, epoch step:54
2022/03/29 14:23:14 - INFO - Distillation -  Global step: 1683, epoch step:63
2022/03/29 14:23:16 - INFO - Distillation -  Global step: 1692, epoch step:72
2022/03/29 14:23:17 - INFO - Distillation -  Global step: 1701, epoch step:81
2022/03/29 14:23:19 - INFO - Distillation -  Global step: 1710, epoch step:90
2022/03/29 14:23:20 - INFO - Distillation -  Global step: 1719, epoch step:99
2022/03/29 14:23:22 - INFO - Distillation -  Global step: 1728, epoch step:108
2022/03/29 14:23:24 - INFO - Distillation -  Global step: 1737, 

tensor([[0.3746],
        [2.6251]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0765],
        [3.8689]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.7594],
        [1.0383]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.7385],
        [3.9580]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.0083],
        [3.2711]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.6278],
        [2.6898]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.7519],
        [2.1307]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.5459],
        [4.3594]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.9338],
        [3.9960]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.9127],
        [3.6011]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[5.3751],
        [4.6441]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.8198],
        [1.0071]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.3227],
        [0.4884]], dev

2022/03/29 14:23:40 - INFO - Distillation -  {'pearson': 0.1271796590684155, 'spearmanr': 0.12484284405152517}
2022/03/29 14:23:40 - INFO - Distillation -  Epoch 10 finished
2022/03/29 14:23:40 - INFO - Distillation -  Epoch 11
2022/03/29 14:23:40 - INFO - Distillation -  Length of current epoch in forward batch: 180
2022/03/29 14:23:41 - INFO - Distillation -  Global step: 1809, epoch step:9
2022/03/29 14:23:43 - INFO - Distillation -  Global step: 1818, epoch step:18
2022/03/29 14:23:44 - INFO - Distillation -  Global step: 1827, epoch step:27
2022/03/29 14:23:46 - INFO - Distillation -  Global step: 1836, epoch step:36
2022/03/29 14:23:48 - INFO - Distillation -  Global step: 1845, epoch step:45
2022/03/29 14:23:49 - INFO - Distillation -  Global step: 1854, epoch step:54
2022/03/29 14:23:51 - INFO - Distillation -  Global step: 1863, epoch step:63
2022/03/29 14:23:53 - INFO - Distillation -  Global step: 1872, epoch step:72
2022/03/29 14:23:55 - INFO - Distillation -  Global step: 

tensor([[0.2648],
        [1.8710]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.0899],
        [3.3422]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.2679],
        [0.4464]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.6689],
        [3.2618]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.9060],
        [2.6550]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.0955],
        [2.3499]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.3423],
        [1.5688]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.4299],
        [4.0073]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.5207],
        [3.8147]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.3652],
        [3.0259]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.7837],
        [4.2723]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.2780],
        [0.6031]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.8659],
        [0.2430]], dev

2022/03/29 14:24:17 - INFO - Distillation -  {'pearson': 0.11446322398932705, 'spearmanr': 0.11222550083580439}
2022/03/29 14:24:17 - INFO - Distillation -  Epoch 11 finished
2022/03/29 14:24:17 - INFO - Distillation -  Epoch 12
2022/03/29 14:24:17 - INFO - Distillation -  Length of current epoch in forward batch: 180


tensor([[3.1623],
        [4.9445]], device='cuda:0', grad_fn=<SliceBackward0>)


2022/03/29 14:24:19 - INFO - Distillation -  Global step: 1989, epoch step:9
2022/03/29 14:24:20 - INFO - Distillation -  Global step: 1998, epoch step:18
2022/03/29 14:24:22 - INFO - Distillation -  Global step: 2007, epoch step:27
2022/03/29 14:24:24 - INFO - Distillation -  Global step: 2016, epoch step:36
2022/03/29 14:24:25 - INFO - Distillation -  Global step: 2025, epoch step:45
2022/03/29 14:24:27 - INFO - Distillation -  Global step: 2034, epoch step:54
2022/03/29 14:24:28 - INFO - Distillation -  Global step: 2043, epoch step:63
2022/03/29 14:24:30 - INFO - Distillation -  Global step: 2052, epoch step:72
2022/03/29 14:24:32 - INFO - Distillation -  Global step: 2061, epoch step:81
2022/03/29 14:24:34 - INFO - Distillation -  Global step: 2070, epoch step:90
2022/03/29 14:24:35 - INFO - Distillation -  Global step: 2079, epoch step:99
2022/03/29 14:24:37 - INFO - Distillation -  Global step: 2088, epoch step:108
2022/03/29 14:24:39 - INFO - Distillation -  Global step: 2097, 

tensor([[0.5057],
        [2.5131]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.6836],
        [3.4547]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.1616],
        [0.7006]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.9997],
        [3.3679]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.7181],
        [3.5510]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.2267],
        [1.8641]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.3783],
        [1.7957]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.8833],
        [3.9538]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.8197],
        [3.9643]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.3299],
        [3.1884]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.5596],
        [4.4845]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.9347],
        [0.9189]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0406],
        [0.4755]], dev

2022/03/29 14:24:54 - INFO - Distillation -  {'pearson': 0.1379913043174405, 'spearmanr': 0.13698671185194836}
2022/03/29 14:24:54 - INFO - Distillation -  Epoch 12 finished
2022/03/29 14:24:54 - INFO - Distillation -  Epoch 13
2022/03/29 14:24:54 - INFO - Distillation -  Length of current epoch in forward batch: 180


tensor([[1.8474],
        [2.8353]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.3734],
        [4.8735]], device='cuda:0', grad_fn=<SliceBackward0>)


2022/03/29 14:24:55 - INFO - Distillation -  Global step: 2169, epoch step:9
2022/03/29 14:24:57 - INFO - Distillation -  Global step: 2178, epoch step:18
2022/03/29 14:24:59 - INFO - Distillation -  Global step: 2187, epoch step:27
2022/03/29 14:25:00 - INFO - Distillation -  Global step: 2196, epoch step:36
2022/03/29 14:25:02 - INFO - Distillation -  Global step: 2205, epoch step:45
2022/03/29 14:25:04 - INFO - Distillation -  Global step: 2214, epoch step:54
2022/03/29 14:25:05 - INFO - Distillation -  Global step: 2223, epoch step:63
2022/03/29 14:25:07 - INFO - Distillation -  Global step: 2232, epoch step:72
2022/03/29 14:25:09 - INFO - Distillation -  Global step: 2241, epoch step:81
2022/03/29 14:25:11 - INFO - Distillation -  Global step: 2250, epoch step:90
2022/03/29 14:25:12 - INFO - Distillation -  Global step: 2259, epoch step:99
2022/03/29 14:25:14 - INFO - Distillation -  Global step: 2268, epoch step:108
2022/03/29 14:25:16 - INFO - Distillation -  Global step: 2277, 

tensor([[0.3739],
        [1.5922]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.0430],
        [3.2531]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.8281],
        [0.3933]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.9456],
        [3.1708]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.9048],
        [2.5584]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.8184],
        [1.1538]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.0791],
        [2.1522]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0883],
        [3.4929]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[1.3348],
        [3.4817]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.1558],
        [2.9991]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.3968],
        [3.7929]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.0335],
        [0.8567]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.4609],
        [1.0140]], dev

2022/03/29 14:25:31 - INFO - Distillation -  {'pearson': 0.15679048327568396, 'spearmanr': 0.1562916699972037}
2022/03/29 14:25:31 - INFO - Distillation -  Epoch 13 finished
2022/03/29 14:25:31 - INFO - Distillation -  Epoch 14
2022/03/29 14:25:31 - INFO - Distillation -  Length of current epoch in forward batch: 180


tensor([[0.9195],
        [3.4407]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[0.9867],
        [2.8336]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[4.0901],
        [2.8829]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[2.2244],
        [2.9538]], device='cuda:0', grad_fn=<SliceBackward0>)
tensor([[3.3252],
        [4.7964]], device='cuda:0', grad_fn=<SliceBackward0>)


2022/03/29 14:25:32 - INFO - Distillation -  Global step: 2349, epoch step:9
2022/03/29 14:25:34 - INFO - Distillation -  Global step: 2358, epoch step:18
2022/03/29 14:25:36 - INFO - Distillation -  Global step: 2367, epoch step:27


KeyboardInterrupt: 

In [23]:
from textbrewer.distiller_utils import move_to_device

In [34]:
test_model = RobertaForSequenceClassification(student_config)
test_model.load_state_dict(torch.load('/work/mhessent/TextBrewer/examples/notebook_examples/saved_models/gs9900.pkl'))#gs4210 is the distilled model weights file

<All keys matched successfully>

In [35]:
from torch.utils.data import DataLoader
eval_dataloader = DataLoader(val_dataset, batch_size=8)

In [37]:
metric= load_metric("glue","stsb")
test_model.to(device)
test_model.eval()
for batch in train_dataloader:
    batch = {k: v for k, v in batch.items()}
    batch = move_to_device(batch,device)
    with torch.no_grad():
        outputs = test_model(**batch)

    logits = outputs.logits
    metric.add_batch(predictions=logits, references=batch["labels"])

metric.compute()

{'pearson': 0.9528690590068446, 'spearmanr': 0.948260299590721}

In [39]:
#teacher_model = RobertaForSequenceClassification.from_pretrained('/work/mhessent/master_thesis/eval_out/roberta-base/stsb/lr3e-05_bs32_epochs10/checkpoint-1620')
metric= load_metric("glue","stsb")
#teacher_model.cpu()
teacher_model.to(device)
teacher_model.eval()
for batch in train_dataloader:
    batch = {k: v for k, v in batch.items()}
    batch = move_to_device(batch,device)
    with torch.no_grad():
        outputs = teacher_model(**batch)

    logits = outputs.logits
    metric.add_batch(predictions=logits, references=batch["labels"])

metric.compute()

{'pearson': 0.9700052119764774, 'spearmanr': 0.9658411506535708}